name: blog

services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '33061:3306'
    volumes:
      - master:/var/lib/mysql
    networks:
      - nestjs_api
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --default-authentication-plugin=mysql_native_password

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    restart: on-failure
    depends_on:
      - mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '33062:3306'
    volumes:
      - slave:/var/lib/mysql
    networks:
      - nestjs_api
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --read-only=ON
      --default-authentication-plugin=mysql_native_password

  redis:
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_DEFAULT_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ${REDIS_PERMISSIONS}'
    networks:
      - nestjs_api

volumes:
  master:
  slave:
  redis:

networks:
  nestjs_api:
    driver: bridge
