name: blog

services:
  master:
    image: mysql:8.0
    container_name: master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33061:3306'
    volumes:
      - master:/var/lib/mysql
    networks:
      - mysql_master_slave
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --default-authentication-plugin=mysql_native_password

  slave:
    image: mysql:8.0
    container_name: slave
    restart: always
    depends_on:
      - master
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33062:3306'
    volumes:
      - slave:/var/lib/mysql
    networks:
      - mysql_master_slave
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --read-only=ON
      --default-authentication-plugin=mysql_native_password

volumes:
  master:
  slave:

networks:
  mysql_master_slave:
    driver: bridge
